name: Trigger auto deployment for turbodiff-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/turbodiff-backend-AutoDeployTrigger-5fcc2e4b-ce22-49a9-8016-04ef346c2e24.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TURBODIFFBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TURBODIFFBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TURBODIFFBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: turbodiffregistry.azurecr.io
          registryUsername: ${{ secrets.TURBODIFFBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TURBODIFFBACKEND_REGISTRY_PASSWORD }}
          containerAppName: turbodiff-backend
          resourceGroup: resource_group_anas
          imageToBuild: turbodiffregistry.azurecr.io/turbodiff-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


